Data Preprocessing and Feature Engineering in Machine Learning

Objective:
This assignment aims to equip you with practical skills in data preprocessing, feature engineering, and feature selection techniques, which are crucial for building efficient machine learning models. You will work with a provided dataset to apply various techniques such as scaling, encoding, and feature selection methods including isolation forest and PPS score analysis.
Dataset:
Given "Adult" dataset, which predicts whether income exceeds $50K/yr based on census data.
Tasks:
1.Handle missing values as per the best practices (imputation, removal, etc.).
●Apply scaling techniques to numerical features:
a.Standard Scaling   b. Min-Max Scaling
●Discuss the scenarios where each scaling technique is preferred and why.
2. Encoding Techniques:
●Apply One-Hot Encoding to categorical variables with less than 5 categories.
●Use Label Encoding for categorical variables. Data Exploration and Preprocessing:
●Load the dataset and conduct basic data exploration (summary statistics, missing values, data types).
●les with more than 5 categories.
●Discuss the pros and cons of One-Hot Encoding and Label Encoding.
3. Feature Engineering:
●Create at least 2 new features that could be beneficial for the model. Explain the rationale behind your choices.
●Apply a transformation (e.g., log transformation) to at least one skewed numerical feature and justify your choice.

In [10]:
import pandas as pd
import numpy as np

In [13]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [14]:
df=pd.read_csv("adult_with_headers (1).csv")

TASK:

1.Handle missing values as per the best practices (imputation, removal, etc.).
●Apply scaling techniques to numerical features:
a.Standard Scaling   b. Min-Max Scaling
●Discuss the scenarios where each scaling technique is preferred and why.

In [16]:
print("Shape:", df.shape)

print("\nFirst 5 Rows:")
print(df.head())

print("\nDataset Information:")
df.info()

print("\nSummary Statistics:")
print(df.describe(include='all'))

print("\nMissing Values:")
print(df.isnull().sum())

Shape: (32561, 15)

First 5 Rows:
   age          workclass  fnlwgt   education  education_num  \
0   39          State-gov   77516   Bachelors             13
1   50   Self-emp-not-inc   83311   Bachelors             13
2   38            Private  215646     HS-grad              9
3   53            Private  234721        11th              7
4   28            Private  338409   Bachelors             13

        marital_status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male
1   Married-civ-spouse     Exec-managerial         Husband   White     Male
2             Divorced   Handlers-cleaners   Not-in-family   White     Male
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female

   capital_gain  capital_loss  hours_per_week  native_country  income
0          2174             0              40   United-States   <=50K
1             0             0              13   United-States   <=50K
2             0             0              40   United-States   <=50K
3             0             0              40   United-States   <=50K
4             0             0              40            Cuba   <=50K

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       32561 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education_num   32561 non-null  int64
 5   marital_status  32561 non-null  object
 6   occupation      32561 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital_gain    32561 non-null  int64
 11  capital_loss    32561 non-null  int64
 12  hours_per_week  32561 non-null  int64
 13  native_country  32561 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB

Summary Statistics:
                 age workclass        fnlwgt education  education_num  \
count   32561.000000     32561  3.256100e+04     32561   32561.000000
unique           NaN         9           NaN        16            NaN
top              NaN   Private           NaN   HS-grad            NaN
freq             NaN     22696           NaN     10501            NaN
mean       38.581647       NaN  1.897784e+05       NaN      10.080679
std        13.640433       NaN  1.055500e+05       NaN       2.572720
min        17.000000       NaN  1.228500e+04       NaN       1.000000
25%        28.000000       NaN  1.178270e+05       NaN       9.000000
50%        37.000000       NaN  1.783560e+05       NaN      10.000000
75%        48.000000       NaN  2.370510e+05       NaN      12.000000
max        90.000000       NaN  1.484705e+06       NaN      16.000000

             marital_status       occupation relationship    race    sex  \
count                 32561            32561        32561   32561  32561
unique                    7               15            6       5      2
top      Married-civ-spouse   Prof-specialty      Husband   White   Male
freq                  14976             4140        13193   27816  21790
mean                    NaN              NaN          NaN     NaN    NaN
std                     NaN              NaN          NaN     NaN    NaN
min                     NaN              NaN          NaN     NaN    NaN
25%                     NaN              NaN          NaN     NaN    NaN
50%                     NaN              NaN          NaN     NaN    NaN
75%                     NaN              NaN          NaN     NaN    NaN
max                     NaN              NaN          NaN     NaN    NaN

        capital_gain  capital_loss  hours_per_week  native_country  income
count   32561.000000  32561.000000    32561.000000           32561   32561
unique           NaN           NaN             NaN              42       2
top              NaN           NaN             NaN   United-States   <=50K
freq             NaN           NaN             NaN           29170   24720
mean     1077.648844     87.303830       40.437456             NaN     NaN
std      7385.292085    402.960219       12.347429             NaN     NaN
min         0.000000      0.000000        1.000000             NaN     NaN
25%         0.000000      0.000000       40.000000             NaN     NaN
50%         0.000000      0.000000       40.000000             NaN     NaN
75%         0.000000      0.000000       45.000000             NaN     NaN
max     99999.000000   4356.000000       99.000000             NaN     NaN

Missing Values:
age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [17]:
(df == '?').sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [19]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [24]:
for col in df.select_dtypes(include=['object']):
    df[col] = df[col].fillna(df[col].mode()[0])

In [26]:
from sklearn.preprocessing import StandardScaler
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
scaler = StandardScaler()
df_standard = df.copy()
df_standard[num_cols] = scaler.fit_transform(df_standard[num_cols])
df_standard[num_cols].head()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
0,0.030671,-1.063611,1.134739,0.148453,-0.21666,-0.035429
1,0.837109,-1.008707,1.134739,-0.145920,-0.21666,-2.222153
2,-0.042642,0.245079,-0.420060,-0.145920,-0.21666,-0.035429
3,1.057047,0.425801,-1.197459,-0.145920,-0.21666,-0.035429
4,-0.775768,1.408176,1.134739,-0.145920,-0.21666,-0.035429

In [27]:
from sklearn.preprocessing import MinMaxScaler
num_cols = df.select_dtypes(include=['int64', 'float64']).columns
scaler = MinMaxScaler()
df_minmax = df.copy()
df_minmax[num_cols] = scaler.fit_transform(df_minmax[num_cols])
df_minmax[num_cols].head()

,age,fnlwgt,education_num,capital_gain,capital_loss,hours_per_week
0,0.301370,0.044302,0.800000,0.02174,0.0,0.397959
1,0.452055,0.048238,0.800000,0.00000,0.0,0.122449
2,0.287671,0.138113,0.533333,0.00000,0.0,0.397959
3,0.493151,0.151068,0.400000,0.00000,0.0,0.397959
4,0.150685,0.221488,0.800000,0.00000,0.0,0.397959

--Standard Scaling
Standard Scaling transforms the data so that it has a mean of 0 and a standard deviation of 1.
It is preferred when the data is approximately normally distributed.
It works well with algorithms such as Logistic Regression, Support Vector Machine (SVM), and K-Nearest Neighbors (KNN).
--Min-Max Scaling
Min-Max Scaling rescales the data to a fixed range of 0 to 1.
It is preferred when the features have different ranges and a fixed scale is required.
It is commonly used with Neural Networks and other distance-based algorithms.

2. Encoding Techniques:
●Apply One-Hot Encoding to categorical variables with less than 5 categories.
●Use Label Encoding for categorical variables. Data Exploration and Preprocessing:
●Load the dataset and conduct basic data exploration (summary statistics, missing values, data types).
●les with more than 5 categories.
●Discuss the pros and cons of One-Hot Encoding and Label Encoding.

In [28]:
cat_cols = df.select_dtypes(include=['object']).columns
for col in cat_cols:
    print(col, ":", df[col].nunique())

workclass : 9
education : 16
marital_status : 7
occupation : 15
relationship : 6
race : 5
sex : 2
native_country : 42
income : 2

In [29]:
onehot_cols = [col for col in cat_cols if df[col].nunique() < 5]

df_onehot = pd.get_dummies(df, columns=onehot_cols)

df_onehot.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,capital_gain,capital_loss,hours_per_week,native_country,sex_ Female,sex_ Male,income_ <=50K,income_ >50K
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,2174,0,40,United-States,False,True,True,False
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,0,0,13,United-States,False,True,True,False
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,0,0,40,United-States,False,True,True,False
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,0,0,40,United-States,False,True,True,False
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,0,0,40,Cuba,True,False,True,False

In [30]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

df_label = df.copy()

label_cols = [col for col in cat_cols if df[col].nunique() >= 5]

for col in label_cols:
    df_label[col] = label_encoder.fit_transform(df_label[col])

df_label.head()

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,sex,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,7,77516,9,13,4,1,1,4,Male,2174,0,40,39,<=50K
1,50,6,83311,9,13,2,4,0,4,Male,0,0,13,39,<=50K
2,38,4,215646,11,9,0,6,1,4,Male,0,0,40,39,<=50K
3,53,4,234721,1,7,2,6,0,2,Male,0,0,40,39,<=50K
4,28,4,338409,9,13,2,10,5,2,Female,0,0,40,5,<=50K

--Pros of One-Hot Encoding
Does not create an ordinal relationship between categories.
Suitable for nominal categorical data.
Improves model performance for many machine learning algorithms.
--Cons of One-Hot Encoding
Increases the number of columns.
Can consume more memory for datasets with many categories.
--Pros of Label Encoding
Simple and memory efficient.
Suitable for ordinal categorical data.
Keeps the number of features unchanged.
--Cons of Label Encoding
Introduces an artificial order among categories.
May reduce model performance for nominal data.

3. Feature Engineering:
●Create at least 2 new features that could be beneficial for the model. Explain the rationale behind your choices.
●Apply a transformation (e.g., log transformation) to at least one skewed numerical feature and justify your choice.

In [31]:
df["total_capital"] = df["capital_gain"] - df["capital_loss"]

In [32]:
df["age_group"] = pd.cut(
    df["age"],
    bins=[0, 25, 40, 60, 100],
    labels=["Young", "Adult", "Middle_Aged", "Senior"]
)

df[["age", "age_group"]].head()

   age    age_group
0   39        Adult
1   50  Middle_Aged
2   38        Adult
3   53  Middle_Aged
4   28        Adult

In [33]:
import numpy as np
df["capital_gain_log"] = np.log1p(df["capital_gain"])
df[["capital_gain", "capital_gain_log"]].head()

   capital_gain  capital_gain_log
0          2174          7.684784
1             0          0.000000
2             0          0.000000
3             0          0.000000
4             0          0.000000

--New Feature 1: Total Capital
Created by subtracting capital_loss from capital_gain.
It represents the overall capital outcome of an individual.
--New Feature 2: Age Group
Created by grouping people into different age categories.
It helps the model identify patterns based on age ranges instead of individual ages.
--Log Transformation
Applied to capital_gain because it is highly skewed.
Log transformation reduces skewness and makes the data more suitable for machine learning models.